plugins {
    id 'application'
    id 'java'
}

group = 'dev.azuremc.deadSignal'
version = '0.1.0-alpha'

repositories {
    mavenCentral()
}

def jmeVersion = '3.9.0-stable'

dependencies {
    implementation "org.jmonkeyengine:jme3-core:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-effects:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-plugins:$jmeVersion"
    runtimeOnly "org.jmonkeyengine:jme3-desktop:$jmeVersion"
    runtimeOnly "org.jmonkeyengine:jme3-lwjgl3:$jmeVersion"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'dev.azuremc.deadsignal.DeadSignalGame'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
